[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
GR_jll = "d2c73de3-f751-5644-a686-071e5b155ba9"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Documenter = "1"
GR_jll = "0.5, 0.6, 0.7, 0.8, 0.9"
